/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfilesIndexImport } from './routes/profiles/index'
import { Route as ProfilesProfileIdImport } from './routes/profiles/$profileId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfilesIndexRoute = ProfilesIndexImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => rootRoute,
} as any)

const ProfilesProfileIdRoute = ProfilesProfileIdImport.update({
  id: '/profiles/$profileId',
  path: '/profiles/$profileId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profiles/$profileId': {
      id: '/profiles/$profileId'
      path: '/profiles/$profileId'
      fullPath: '/profiles/$profileId'
      preLoaderRoute: typeof ProfilesProfileIdImport
      parentRoute: typeof rootRoute
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/profiles': typeof ProfilesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/profiles': typeof ProfilesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/profiles/': typeof ProfilesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profiles/$profileId' | '/profiles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profiles/$profileId' | '/profiles'
  id: '__root__' | '/' | '/profiles/$profileId' | '/profiles/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfilesProfileIdRoute: typeof ProfilesProfileIdRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfilesProfileIdRoute: ProfilesProfileIdRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/profiles/$profileId",
        "/profiles/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/profiles/$profileId": {
      "filePath": "profiles/$profileId.jsx"
    },
    "/profiles/": {
      "filePath": "profiles/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
